### ISSUE TITLE
Corrupt Files

### ISSUE THREAD

**Issue by ikenna-oluigbo** [ricardovvargas/3w_dataset#1]
After downloading, i get an error message 'The Archive is Corrupt'  when i try to launch the file. 
Can this be fixed?

**Comment by M1ndas** [comment]
@ikenna-oluigbo this isnt'a corrupted file, this is what is called a split-zip file. You need to download them all and then start extracting the first one for all the files to be extracted successfully into one folder. Hope this helps.

**Comment by ricardovvargas** [comment]
@MindaugasBernatavicius, you're right. Thanks for this help.
