### ISSUE TITLE
do you know repo for with code  for multivariate time series prediction   both regression and classification

### ISSUE THREAD

**Issue by Sandy4321** [ricardovvargas/3w_dataset#2]
great data thanks

only 
1
can you share pdf of paper?
2
do you know repo for with code  for multivariate time series prediction   both regression and classification

each row means the time series, and columns represent different continues or/and discrete/category observation.
 
1 
  where all values are continues values 
         weight    height     age   target 
time 1|   56        160    34        1.2
time 2|   77        170    54        3.5
time 3|   87        167     43       0.7
time 4|   55        198    72        0.5
time 5|   88        176     32       2.3
etc

2
or  even will it work for multivariate time series where values are mixture of continues  and categorical values
for example 2 dimensions have continues values and 3 dimensions are categorical values

			color        weight     gender  height  age      target 
time 1|    black       56             m   160    34         yes
time 2|    white       77             f   170    54         no
time 3|   yellow      87             m   167    43          yes
time 4|    white       55             m   198    72         no
time 5|   white       88              f   176    32         yes

**Comment by ricardovvargas** [comment]
Sorry about the late, @Sandy4321.

1) Yes, I can share the PDF of our paper with you. As I don't have your e-mail, can you please send me a message (ricardovvargas@gmail.com)?

2) No, I am not aware of any repository with code for multivariate time series prediction both regression and classification. I know only some packets that do parts of the job.

Ricardo Vargas

**Comment by Sandy4321** [comment]
I am not aware of any repository with code for multivariate time series prediction both regression and classification. I know only some packets that do parts of the job.

super
can you share links to these packets , please

**Comment by ricardovvargas** [comment]
The PDF of our paper is attached here.

There is a good list of packages related to time series in this link:
https://github.com/MaxBenChrist/awesome_time_series_in_python.

Sorry about the late.

Ricardo Vargas

**Comment by Sandy4321** [comment]
it is written 
The PDF of our paper is attached here.
but there is no paper

also I sent you email with subject
paper for Fwd: [ricardovvargas/3w_dataset] do you know repo for with code for multivariate time series prediction both regression and classification (#2)

thanks

**Comment by Syx5290** [comment]
Dear Professor

last time ,maybe I did not express what i mean.I&nbsp;am doing the project is about oil spill recognition,i really need the oil spill image to train my CNNs.&nbsp;I &nbsp;am a newer,i have 't&nbsp;&nbsp;know the CSV files before,and i don't know what&nbsp; the 3w_data is about.&nbsp;I want make sure the CSV file is the time series about oil leakage or&nbsp; it&nbsp; can translate into image that have the content about oil leakage scene.　I really need the oil spii image but it can hardly find.Do you know some repositories&nbsp; about oil leakage image dataset?&nbsp; and&nbsp; i&nbsp; will be grateful to you .I am looking forward to your replay!Thanks!

&nbsp;Xue&nbsp; Shi





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ricardovvargas/3w_dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 凌晨3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ricardovvargas/3w_dataset] do you know repo for with code  for multivariate time series prediction   both regression and classification (#2)





 
it is written
 The PDF of our paper is attached here.
 but there is no paper
 
also I sent you email with subject
 paper for Fwd: [ricardovvargas/3w_dataset] do you know repo for with code for multivariate time series prediction both regression and classification (#2)
 
thanks

**Comment by ricardovvargas** [comment]
The 3W dataset is not related to oil leakage ou any type of image. I don't
know any repository about oil leakage. Sorry, I can't help you.

Ricardo Vargas
