### ISSUE TITLE
Tables on anomaly detection benchmark

### ISSUE THREAD

**Issue by AlephNullVEVO** [ricardovvargas/3w_dataset#3]
Each classifier has the same value for f1, precision and recall in section 3.1 of the anomaly detection benchmark. Is this normal?
![image](https://user-images.githubusercontent.com/89750447/146968023-12713a52-8df5-4f33-94e5-bc33529d098f.png)

**Comment by ricardovvargas** [comment]
Hi. Yes, this is normal. The use of average='micro' is responsible for that. You can try other averaging methods and compare the results.

**Comment by AlephNullVEVO** [comment]
Wouldn't it be better to use average='binary', since we are dealing with binary classification (normal/abnormal)? From what I researched, f1-micro = precision-micro = recall-micro = accuracy. Or was accuracy the evaluation metric all along?

**Comment by ricardovvargas** [comment]
I believe that each type of average has its particularities and interpretation. Even in a binary classification problem, it is possible to use other type besides 'binary', that reports results for the positive class only. As we wanted to consider also the negative class, we choose 'micro'. Nowadays, 'weighted' would be my first choice.
